import { translate } from "./translate.mjs";

const translateButton = document.querySelector('#translate-btn');
const text1 = document.querySelector('.freedom p');
const text1_sp = localStorage.getItem("text1_sp");
const text2 = document.querySelector('.freedom h2');
const text2_sp = localStorage.getItem("text2_sp");
const text3 = document.querySelector('.freedom cite');
const text3_sp = localStorage.getItem("text3_sp");
const text4 = document.querySelector('h1');
const text4_sp = localStorage.getItem("text4_sp");
const text5 = document.querySelector('#israel_btn');
const text5_sp = localStorage.getItem("text5_sp");
const text6 = document.querySelector('#nephites_btn');
const text6_sp = localStorage.getItem("text6_sp");
const text7 = document.querySelector('#us_btn');
const text7_sp = localStorage.getItem("text7_sp");
const text8 = document.querySelector('#israel h3');
const text8_sp = localStorage.getItem("text8_sp");
const text9 = document.querySelector('#israel p');
const text9_sp = localStorage.getItem("text9_sp");
const text10 = document.querySelector('#nephites h3');
const text10_sp = localStorage.getItem("text10_sp");
const text11 = document.querySelector('#nephites i');
const text11_sp = localStorage.getItem("text11_sp");
const text12 = document.querySelector('#nephites p');
const text12_sp = localStorage.getItem("text12_sp");
const text13 = document.querySelector('#us h3');
const text13_sp = localStorage.getItem("text13_sp");
const text14 = document.querySelector('#us i');
const text14_sp = localStorage.getItem("text14_sp");
const text15 = document.querySelector('#us p');
const text15_sp = localStorage.getItem("text15_sp");
const text16 = document.querySelector('#curse h2');
const text16_sp = localStorage.getItem("text16_sp");
const text17 = document.querySelector('#curse i');
const text17_sp = localStorage.getItem("text17_sp");
const text18 = document.querySelector('#curse p');
const text18_sp = localStorage.getItem("text18_sp");
const text19 = document.querySelector('#balaam h2');
const text19_sp = localStorage.getItem("text19_sp");
const text20 = document.querySelector('#balaam p');
const text20_sp = localStorage.getItem("text20_sp");
const text21 = document.querySelector('#balaam i');
const text21_sp = localStorage.getItem("text21_sp");
const text22 = document.querySelector('.visit a');
const text22_sp = localStorage.getItem("text22_sp");


translateButton.addEventListener('click', async () => {

    translate(text1, text1_sp, "text1_sp");
    translate(text2, text2_sp, "text2_sp");
    translate(text3, text3_sp, "text3_sp");
    translate(text4, text4_sp, "text4_sp");
    translate(text5, text5_sp, "text5_sp");
    translate(text6, text6_sp, "text6_sp");
    translate(text7, text7_sp, "text7_sp");
    translate(text8, text8_sp, "text8_sp");
    translate(text9, text9_sp, "text9_sp");
    translate(text10, text10_sp, "text10_sp");
    translate(text11, text11_sp, "text11_sp");
    translate(text12, text12_sp, "text12_sp");
    translate(text13, text13_sp, "text13_sp");
    translate(text14, text14_sp, "text14_sp");
    translate(text15, text15_sp, "text15_sp");
    translate(text16, text16_sp, "text16_sp");
    translate(text17, text17_sp, "text17_sp");
    translate(text18, text18_sp, "text18_sp");
    translate(text19, text19_sp, "text19_sp");
    translate(text20, text20_sp, "text20_sp");
    translate(text21, text21_sp, "text21_sp");
    translate(text22, text22_sp, "text22_sp");

    translateButton.textContent = "Inglés";
    translateButton.addEventListener('click', () => location.reload());
});

const element = document.querySelector("article");
element.classList.add("visible"); 